### ISSUE TITLE
build fails on node 10.x.x

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#939]
Here's my full log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/samanbemelbenrud/.nvm/versions/node/v10.16.0/bin/node',
1 verbose cli   '/Users/samanbemelbenrud/.nvm/versions/node/v10.16.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @mapbox/assembly@0.23.2~prestart: @mapbox/assembly@0.23.2
6 info lifecycle @mapbox/assembly@0.23.2~start: @mapbox/assembly@0.23.2
7 verbose lifecycle @mapbox/assembly@0.23.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle @mapbox/assembly@0.23.2~start: PATH: /Users/samanbemelbenrud/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/samanbemelbenrud/work-repos/assembly/node_modules/.bin:/Users/samanbemelbenrud/.nvm/versions/node/v10.16.0/bin:/Users/samanbemelbenrud/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/samanbemelbenrud/gems/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle @mapbox/assembly@0.23.2~start: CWD: /Users/samanbemelbenrud/work-repos/assembly
10 silly lifecycle @mapbox/assembly@0.23.2~start: Args: [ '-c',
10 silly lifecycle   'concurrently -k -p "{name}" -n "Batfish ,Assembly" "npm run build:css && npm run build:js && npm run generate-site-data && batfish start" "node scripts/watch-assembly-assets.js"' ]
11 silly lifecycle @mapbox/assembly@0.23.2~start: Returned: code: 1  signal: null
12 info lifecycle @mapbox/assembly@0.23.2~start: Failed to exec start script
13 verbose stack Error: @mapbox/assembly@0.23.2 start: `concurrently -k -p "{name}" -n "Batfish ,Assembly" "npm run build:css && npm run build:js && npm run generate-site-data && batfish start" "node scripts/watch-assembly-assets.js"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/samanbemelbenrud/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/samanbemelbenrud/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @mapbox/assembly@0.23.2
15 verbose cwd /Users/samanbemelbenrud/work-repos/assembly
16 verbose Darwin 18.2.0
17 verbose argv "/Users/samanbemelbenrud/.nvm/versions/node/v10.16.0/bin/node" "/Users/samanbemelbenrud/.nvm/versions/node/v10.16.0/bin/npm" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @mapbox/assembly@0.23.2 start: `concurrently -k -p "{name}" -n "Batfish ,Assembly" "npm run build:css && npm run build:js && npm run generate-site-data && batfish start" "node scripts/watch-assembly-assets.js"`
22 error Exit status 1
23 error Failed at the @mapbox/assembly@0.23.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Going to guess it's an issue with Batfish, potentially https://github.com/mapbox/batfish/issues/299.

**Comment by davidtheclark** [comment]
A more recent version of Batfish works with Node 10, thanks to @mapbox/docs.
